name: Auto Create PR on Push

on:
  push:
    branches-ignore:
      - main  # Avoid triggering PR creation when pushing to main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}  # Uses the branch that triggered the push
          base: main
          title: "Auto PR: Merging ${{ github.ref_name }} into main"
          body: "This PR merges the latest changes from ${{ github.ref_name }} into main and closes linked issues."
          draft: false
          delete-branch: true  # Deletes the branch after merging
